/**
 * Code generated by protoc-gen-twirp_js v5.0.0, DO NOT EDIT.
 * source: haberdasher.proto
 */
// import our twirp js library dependency
var createClient = require("twirp");
// import our protobuf definitions
var pb = require("./haberdasher_pb.js");
Object.assign(module.exports, pb);

/**
 * Haberdasher service makes hats for clients.
 */
module.exports.createHaberdasherServiceClient = function(baseurl, extraHeaders, useJSON) {
    var rpc = createClient(baseurl, "haberdasher.HaberdasherService", "v5.0.0",  useJSON, extraHeaders === undefined ? {} : extraHeaders);
    return {
        /**
         * MakeHat produces a hat of mysterious, randomly-selected color!
         */
        makeHat: function(data) { return rpc("MakeHat", data, pb.Hat); }
    }
}

