---
kind: pipeline
type: docker
name: build

workspace:
  path: /microservice

steps:
- name: codegen
  image: tullo/microservice-build
  pull: always
  commands:
  - make rpc
  - make templates

- name: migrations
  image: percona/percona-server:8.0.22
  user: root
  pull: always
  commands:
  - yum -q -y install make
  - "bash -c 'while : ; do  sleep 1 ; $(cat < /dev/null > /dev/tcp/mysql-test/3306) && break ; done' 2>/dev/null"
  - make migrate

- name: build
  image: tullo/microservice-build
  pull: always
  commands:
  - wire ./...
  - make tidy
  - make lint
  - make build
  - make build-cli

services:
- name: mysql-test
  pull: always
  image: percona/percona-server:8.0.22
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: default
