---
kind: pipeline
type: docker
name: build

workspace:
  path: /microservice

steps:
- name: codegen
  image: tullo/microservice-build
  pull: always
  user: 1000
  commands:
  - make rpc
  - make templates
  - make build-cli
  - make migrate

- name: build
  image: tullo/microservice-build
  pull: always
  user: 1000
  commands:
  - wire ./...
  - make tidy
  - make lint
  - make build

services:
- name: mysql-test
  pull: always
  image: percona/percona-server:8.0.17
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: default
    MYSQL_USER: migrations
    MYSQL_PASSWORD: migrations
    MYSQL_DATABASE: migrations
