---
kind: pipeline
type: docker
name: build

workspace:
  path: /microservice

steps:
- name: codegen
  image: tullo/microservice-build
  pull: always
  commands:
  - make rpc
  - make templates
  - go mod tidy > /dev/null 2>&1
  - go fmt ./... > /dev/null 2>&1
  - make build
  - make build-cli
