version: '3.4'

services:
  apm:
    build:
      context: docker/apm

  db:
    command:
    - --max_connections=1000
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: stats
      MYSQL_PASSWORD: stats
      MYSQL_USER: stats
    image: percona/percona-server:8.0.22
    restart: always

  elk:
    image: sebp/elk:7.10.0
    ports:
    - published: 5601
      target: 5601
    - published: 9200
      target: 9200
    - published: 5044
      target: 5044
    restart: always

  stats:
    command:
    - --migrate-db-dsn=stats:stats@tcp(db:3306)/stats
    - --migrate
    environment:
      DB_DSN: stats:stats@tcp(db:3306)/stats
      ELASTIC_APM_SERVER_URL: http://apm:8200
      ELASTIC_APM_SERVICE_NAME: stats
#     ELASTIC_APM_SPAN_FRAMES_MIN_DURATION=5ms  https://www.elastic.co/guide/en/apm/agent/go/current/configuration.html
    image: tullo/service-stats
    restart: always
