version: '3.4'

# cat .env
# https://dev.mysql.com/doc/refman/8.0/en/charset-mysql.html
# https://dev.mysql.com/doc/refman/8.0/en/charset-collation-names.html
# https://dev.mysql.com/doc/refman/8.0/en/charset-server.html
# https://www.mysqltutorial.org/mysql-collation/

services:
  apm:
    build:
      context: docker/apm

  db:
    image: percona/percona-server:8.4.5
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_danish_ci
    - --default-authentication-plugin=mysql_native_password
    - --max_connections=1000
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    restart: always
    volumes:
    - ./docker/dev/initdb.d:/docker-entrypoint-initdb.d:rw

  elk:
    image: sebp/elk:8.17.8
    ports:
    - published: 5601
      target: 5601
    restart: always

  stats:
    image: ${IMAGE_PREFIX}stats
#    image: titpetric/service-stats
    command:
    - --migrate-db-dsn=stats:stats@tcp(db:3306)/stats
    - --migrate
    environment:
      DB_DSN: stats:stats@tcp(db:3306)/stats
      ELASTIC_APM_SERVER_URL: http://apm:8200
      ELASTIC_APM_SERVICE_NAME: stats
#     ELASTIC_APM_SPAN_FRAMES_MIN_DURATION=5ms  https://www.elastic.co/guide/en/apm/agent/go/current/configuration.html
    restart: always

  hd:
    image: ${IMAGE_PREFIX}haberdasher
    command:
    - --migrate-db-dsn=haberdasher:haberdasher@tcp(db:3306)/haberdasher
    - --migrate
    environment:
      DB_DSN: haberdasher:haberdasher@tcp(db:3306)/haberdasher
      ELASTIC_APM_SERVER_URL: http://apm:8200
      ELASTIC_APM_SERVICE_NAME: haberdasher
    restart: always
