package haberdasher

// file is autogenerated, do not modify here, see
// generator and template: templates/client_client.go.tpl

import (
	"net/http"

	"github.com/tullo/microservice/rpc/haberdasher"
)

// New creates a Haberdasher RPC client.
func New() haberdasher.HaberdasherService {
	return NewCustom("http://haberdasher.service:3000", &http.Client{})
}

// NewCustom creates a Haberdasher RPC client with custom Address/HTTP Client.
func NewCustom(addr string, client haberdasher.HTTPClient) haberdasher.HaberdasherService {
	return haberdasher.NewHaberdasherServiceJSONClient(addr, client)
}
