version: '3.4'

services:

  db:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: stats
      MYSQL_PASSWORD: stats
      MYSQL_USER: stats
    image: percona/percona-server:8.0.34
    restart: always

  migrations:
    command:
    - -db-dsn=stats:stats@tcp(db:3306)/stats
    - -service=stats
    - -real=true
    image: titpetric/service-db-migrate-cli

  stats:
    command:
    - --migrate-db-dsn=stats:stats@tcp(db:3306)/stats
    - --migrate
    environment:
      DB_DSN: stats:stats@tcp(db:3306)/stats
    image: tullo/service-stats
    restart: always

