package main

// file is autogenerated, do not modify here, see
// generator and template: templates/cmd_main.go.tpl

import (
	"flag"
	"log"

	"net/http"

	"github.com/SentimensRG/sigctx"
	_ "github.com/go-sql-driver/mysql"
	"${MODULE}/db"
	"${MODULE}/internal"
	"${MODULE}/rpc/${SERVICE}"
	server "github.com/tullo/microservice/server/stats"
)

func main() {
	var config struct {
		migrate bool
		opt     db.ConnectionOptions
	}
	flag.StringVar(&config.opt.DB.Driver, "migrate-db-driver", "mysql", "Migrations: Database driver")
	flag.StringVar(&config.opt.DB.DSN, "migrate-db-dsn", "", "Migrations: DSN for database connection")
	flag.BoolVar(&config.migrate, "migrate", false, "Run migrations?")
	flag.Parse()

	ctx := sigctx.New()

	if config.migrate {
		handle, err := db.ConnectWithRetry(ctx, config.opt)
		if err != nil {
			log.Fatalf("Error connecting to database: %+v", err)
		}
		if err := db.Run("stats", handle); err != nil {
			log.Fatalf("An error occured: %+v", err)
		}
	}

	srv, err := server.New(ctx)
	if err != nil {
		log.Fatalf("Error in service.New(): %+v", err)
	}

	twirpHandler := ${SERVICE}.New${SERVICE_CAMEL}ServiceServer(srv, nil)

	http.ListenAndServe(":3000", internal.WrapWithIP(twirpHandler))
}
