// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package stats

import (
	"context"
	"github.com/tullo/microservice/db"
	"github.com/tullo/microservice/inject"
)

// Injectors from wire.go:

func New(ctx context.Context) (*Server, error) {
	sqlxDB, err := db.Connect(ctx)
	if err != nil {
		return nil, err
	}
	sonyflake := inject.Sonyflake()
	flusher, err := NewFlusher(ctx, sqlxDB)
	if err != nil {
		return nil, err
	}
	server := &Server{
		db:        sqlxDB,
		sonyflake: sonyflake,
		flusher:   flusher,
	}
	return server, nil
}
