package main

// file is autogenerated, do not modify here, see
// generator and template: templates/cmd_main.go.tpl

import (
	"context"
	"log"

	"net/http"

	_ "github.com/go-sql-driver/mysql"

	"github.com/tullo/microservice/internal"
	"github.com/tullo/microservice/rpc/stats"
	server "github.com/tullo/microservice/server/stats"
)

func main() {
	ctx := context.TODO()

	srv, err := server.New(ctx)
	if err != nil {
		log.Fatalf("Error in service.New(): %+v", err)
	}

	twirpHandler := stats.NewStatsServiceServer(srv, nil)

	http.ListenAndServe(":3000", internal.WrapWithIP(twirpHandler))
}
